on:
  push:
    branches: [main]
  pull_request:
    types: [opened, repoened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: gleam-lang/setup-erlang@v1.1.3
        with:
          otp-version: "27"
      - run: make test PROFILE=ci
