{application,remote_fun,
             [{description,"Remote function"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{remote_fun_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[remote_fun_client,remote_fun_server]},
              {maintainers,[]},
              {licenses,["MIT"]},
              {links,[]}]}.
