on:
  push:
    branches: [main]
  pull_request:
    types: [opened, repoened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Setup erlang
        run: cd sequential/installing && nix-shell
      - run: make test PROFILE=ci
