on:
  push:
    branches: [main]
  pull_request:
    types: [opened, repoened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0.1"
          rebar3-version: "3.23.0"
      - run: make test PROFILE=ci
